apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd
  labels:
    app: react-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-cicd
  template:
    metadata:
      labels:
        app: react-cicd
    spec:
      containers:
        - name: react-cicd
          image: pavanitla/react-cicd:latest  # this gets replaced by GitHub Actions
          ports:
            - containerPort: 80
          imagePullPolicy: Always   # ðŸ‘ˆ forces pulling the latest image each time
      restartPolicy: Always