apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-cicd
  template:
    metadata:
      labels:
        app: react-cicd
    spec:
      containers:
      - name: react-cicd
        image: <your-aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/react-cicd:latest
        imagePullPolicy: Always   # ðŸ‘ˆ add this line
        ports:
        - containerPort: 80
