apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-cicd
  template:
    metadata:
      labels:
        app: react-cicd
    spec:
      containers:
        - name: react-cicd
          image: itlapav/react-cicd:latest  # Replace with your Docker Hub image
          ports:
            - containerPort: 80
